const express = require('express');
const nodemailer = require('nodemailer');
const router = express.Router();

function buildHtml(plan) {
  const days = plan.map(meal => `
    <div style="margin-bottom:32px;">
      <h2 style="margin:0 0 4px;color:#1b5e20;font-size:1.1rem;">${meal.day}</h2>
      <p style="margin:0 0 12px;font-size:1.3rem;font-weight:600;">${meal.title}</p>
      <span style="display:inline-block;background:#e8f5e9;color:#2e7d32;padding:3px 10px;border-radius:999px;font-size:0.8rem;font-weight:600;text-transform:uppercase;letter-spacing:0.03em;margin-bottom:16px;">${meal.cookingMethod}</span>
      <p style="margin:0 0 4px;color:#666;font-size:0.85rem;">${meal.servings} servings</p>

      <h3 style="margin:16px 0 8px;font-size:0.95rem;color:#333;">Ingredients</h3>
      <ul style="margin:0 0 16px;padding-left:20px;line-height:1.7;color:#444;">
        ${meal.ingredients.map(i => `<li>${i}</li>`).join('')}
      </ul>

      <h3 style="margin:0 0 8px;font-size:0.95rem;color:#333;">Instructions</h3>
      <ol style="margin:0;padding-left:20px;line-height:1.8;color:#444;">
        ${meal.instructions.map(s => `<li>${s}</li>`).join('')}
      </ol>
    </div>
  `).join('<hr style="border:none;border-top:1px solid #eee;margin:0 0 32px;">');

  return `
    <div style="font-family:system-ui,sans-serif;max-width:600px;margin:0 auto;padding:32px 24px;color:#1a1a1a;">
      <h1 style="font-size:1.8rem;color:#1b5e20;margin:0 0 8px;">Your Week of Dinners</h1>
      <p style="color:#666;margin:0 0 32px;">Generated by FoodSaver</p>
      ${days}
    </div>
  `;
}

router.post('/mealplan', async (req, res) => {
  const { plan } = req.body;
  if (!plan || !Array.isArray(plan)) {
    return res.status(400).json({ error: 'plan array required' });
  }

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_APP_PASSWORD,
    },
  });

  try {
    await transporter.sendMail({
      from: `FoodSaver <${process.env.EMAIL_USER}>`,
      to: process.env.EMAIL_USER,
      subject: "This Week's Dinners — FoodSaver",
      html: buildHtml(plan),
    });
    res.json({ ok: true });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to send email' });
  }
});

module.exports = router;
